on:
  push:
jobs:
  build:
      name: Build executable ğŸ“¦
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              python -m pip install .[dev] pyinstaller
      - name: Lint code ğŸ¦„
        run: tox -e lint
      - name: Build binary ğŸ”¢
        run:  pyinstaller "main.spec"
      - name: Upload generated binary ğŸ‘©â€ğŸ’»
        uses: actions/upload-artifact@v4
        with:
          name: generated-excutable
          path: .\dist\ms_teams_parser.exe
          retention-days: 1
      - name: Run conversion â†©ï¸
        run: |
             .\dist\ms_teams_parser.exe -f ".\forensicsim-data\jane_doe_v_1_4_00_11161\IndexedDB\https_teams.microsoft.com_0.indexeddb.leveldb" -o "jane_doe_v_1_4_00_11161.json"
             .\dist\ms_teams_parser.exe -f ".\forensicsim-data\john_doe_v_1_4_00_11161\IndexedDB\https_teams.microsoft.com_0.indexeddb.leveldb" -o "john_doe_v_1_4_00_11161.json"
             .\dist\ms_teams_parser.exe -f ".\forensicsim-data\karelze_v_23306_3309_2530_1346\IndexedDB\https_teams.live.com_0.indexeddb.leveldb" -o "karelze_v_23306_3309_2530_1346.json"
      - name: Upload resultsğŸ“²
        uses: actions/upload-artifact@v4
        with:
          name: generated-outputs
          path: |
                   jane_doe_v_1_4_00_11161.json
                   john_doe_v_1_4_00_11161.json
                   karelze_v_23306_3309_2530_1346.json
          retention-days: 1
      - name: Test calling script ğŸ–±ï¸
        run: |
              python tools/main.py --help
              python tools/dump_leveldb.py --help
              python tools/dump_localstorage.py --help
              python tools/dump_sessionstorage.py --help