on:
    push:
jobs:
    build:
      name: Build exectuable ğŸ“¦
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              python -m pip install .[dev] pyinstaller
      - name: Lint code ğŸ¦„
        run: tox -e lint
      - name: Build binary ğŸ”¢
        run:  pyinstaller "main.spec"
      - name: Run conversion â†©ï¸
        run: |
             .\dist\ms_teams_parser.exe -f ".\forensicsim-data\jane_doe_v_1_4_00_11161\IndexedDB\https_teams.microsoft.com_0.indexeddb.leveldb" -o "jane_doe_v_1_4_00_11161.json"
             .\dist\ms_teams_parser.exe -f ".\forensicsim-data\john_doe_v_1_4_00_11161\IndexedDB\https_teams.microsoft.com_0.indexeddb.leveldb" -o "john_doe_v_1_4_00_11161.json"
      - name: Upload resultsğŸ“²
        uses: actions/upload-artifact@v4
        with:
          name: generated-outputs
          path: |
              jane_doe_v_1_4_00_11161.json
              john_doe_v_1_4_00_11161.json
          retention-days: 1
      - name: Test calling script ğŸ“
        run: |
              python tools/main.py --help
              python tools/dump_leveldb.py --help
              python tools/dump_localstorage.py --help
              python tools/dump_sessionstorage.py --help
      - name: Calculate diff ğŸ‘½
        run: | 
            git diff --no-index --word-diff .\forensicsim-data\expected-result\jane_doe_v_1_4_00_11161.json jane_doe_v_1_4_00_11161.json
            git diff --no-index --word-diff .\forensicsim-data\expected-result\john_doe_v_1_4_00_11161.json john_doe_v_1_4_00_11161.json